"""progress tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 15:37:40.033219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_settings",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("scheduling", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_unit", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("learner_id", "course_id"),
    )
    op.create_table(
        "learner_settings",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("theme", sa.String(), nullable=False),
        sa.Column("show_key_hints", sa.Boolean(), nullable=False),
        sa.Column("time_zone", sa.String(), nullable=False),
        sa.Column("prefs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("learner_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_day", sa.Date(), nullable=True),
        sa.CheckConstraint("mode IN ('quiz', 'flashcards', 'exercise')", name="ck_sessions_mode"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sessions_learner_course_day",
        "sessions",
        ["learner_id", "course_id", "completed_day"],
        unique=False,
    )
    op.create_table(
        "cards",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("due", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("ease", sa.Double(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("last_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_rating", sa.String(), nullable=True),
        sa.Column("leech", sa.Boolean(), nullable=False),
        sa.Column("suspended", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('question', 'exercise')", name="ck_cards_kind"),
        sa.CheckConstraint(
            "last_rating IS NULL OR last_rating IN ('again', 'hard', 'good', 'easy')",
            name="ck_cards_last_rating",
        ),
        sa.CheckConstraint("phase IN ('new', 'learning', 'review', 'relearning')", name="ck_cards_phase"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("learner_id", "item_id"),
    )
    op.create_index("ix_cards_learner_course_due", "cards", ["learner_id", "course_id", "due"], unique=False)
    op.create_table(
        "exercise_states",
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("attempt", sa.String(), nullable=False),
        sa.Column("attempt_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tests_passed", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("hints_revealed", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempt IN ('first', 'redo', 'quick')", name="ck_exercise_attempt"),
        sa.CheckConstraint(
            "status IN ('not-started', 'in-progress', 'done', 'skipped')", name="ck_exercise_status"
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("learner_id", "item_id"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rating", sa.String(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("hinted", sa.Boolean(), nullable=False),
        sa.Column("overridden", sa.Boolean(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("rating IN ('again', 'hard', 'good', 'easy')", name="ck_reviews_rating"),
        sa.CheckConstraint("source IN ('quiz', 'flashcard', 'exercise')", name="ck_reviews_source"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["learner_id"], ["learners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reviews_learner_course_at", "reviews", ["learner_id", "course_id", "at"], unique=False
    )
    op.create_index("ix_reviews_learner_item", "reviews", ["learner_id", "item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_learner_item", table_name="reviews")
    op.drop_index("ix_reviews_learner_course_at", table_name="reviews")
    op.drop_table("reviews")
    op.drop_table("exercise_states")
    op.drop_index("ix_cards_learner_course_due", table_name="cards")
    op.drop_table("cards")
    op.drop_index("ix_sessions_learner_course_day", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("learner_settings")
    op.drop_table("course_settings")
    # ### end Alembic commands ###
